#!/usr/bin/env node
/**
 * Bundles the runtime (page-side) into a single IIFE, inlines it into a
 * shell HTML document, and writes `runtime.bundle.ts` exporting the result.
 *
 * The bundle is committed so consumers don't need a build step.
 */
import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENTRY = join(__dirname, "runtime", "index.ts");
const STYLES = join(__dirname, "svg-styles.ts");
const OUT = join(__dirname, "runtime.bundle.ts");

async function loadSvgStyles() {
  // svg-styles.ts exports a string constant. Cheaper than running TS to
  // read it: pluck it out with a regex. It's a static literal so this is fine.
  const src = await readFile(STYLES, "utf8");
  const m = src.match(/export const SVG_STYLES\s*=\s*`([\s\S]*?)`/);
  if (!m) throw new Error("Could not extract SVG_STYLES from svg-styles.ts");
  return m[1];
}

async function main() {
  const svgStyles = await loadSvgStyles();

  const result = await build({
    entryPoints: [ENTRY],
    bundle: true,
    minify: true,
    format: "iife",
    target: ["es2022"],
    platform: "browser",
    write: false,
    logLevel: "warning",
  });
  const js = result.outputFiles[0].text;

  const shell = `<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Widget</title>
<style>
*{box-sizing:border-box}
body{margin:0;padding:1rem;font-family:system-ui,-apple-system,sans-serif;background:#1a1a1a;color:#e0e0e0;}
@keyframes _glimpseUiFadeIn{from{opacity:0;transform:translateY(4px);}to{opacity:1;transform:none;}}
${svgStyles}
</style>
</head><body><div id="root"></div>
<script>${js}</script>
</body></html>`;

  const hash = createHash("sha256").update(shell).digest("hex").slice(0, 12);

  const header = `// AUTO-GENERATED by build.mjs — do not edit by hand.
// Run \`npm run build:runtime\` to regenerate.
// Hash: ${hash}

`;

  // Escape for a TS template literal: backslashes, backticks, ${ }.
  const escaped = shell.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

  const out = `${header}export const RUNTIME_VERSION = "${hash}";\nexport const RUNTIME_HTML = \`${escaped}\`;\n`;
  await writeFile(OUT, out, "utf8");

  const kb = (Buffer.byteLength(shell, "utf8") / 1024).toFixed(1);
  console.log(`built runtime.bundle.ts — ${kb} KB, hash ${hash}`);
}

main().catch((err) => { console.error(err); process.exit(1); });
